# Generated by Django 3.0.4 on 2020-03-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='contador',
            field=models.IntegerField(default=0),
        ),
    ]
